version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
    image: laravel-app:latest
    container_name: laravel-app
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: