version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - php-fpm
      - nginx

  php-fpm:
    image: php:8.1.29-fpm
    volumes:
      - .:/app
    environment:
      - PHP_IDE_CONFIG=serverName=docker

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - .docker/default.conf:/etc/nginx/conf.d/default.conf  # Ajuste o caminho conforme necessário
    depends_on:
      - php-fpm

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: