name: Laravel Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Composer
        uses: ./.github/actions/composer

      - name: Setup Database Config
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "8.0"
          mysql database: "test"
          mysql root password: "secret"

      - name: Prepare Laravel Environment
        env:
            APP_ENV: testing
            DB_CONNECTION: mysql
            DB_DATABASE: test
            DB_USERNAME: root
            DB_PASSWORD: secret
        run: |
            cp .env.example .env
            php artisan cache:clear
            php artisan config:clear
            php artisan key:generate
            php artisan migrate --seed
            php artisan storage:link
            chmod -R 777 storage bootstrap/cache

      - name: Run Test with Pest
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: test
          DB_PORT: 3306
          DB_PASSWORD: secret
          DB_USERNAME: root
        run: ./vendor/bin/pest
