name: Laravel Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: testdatabase
          MYSQL_ROOT_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify MySQL connection
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uuser -psecret -e "SHOW DATABASES"

      - name: Install Composer
        uses: ./.github/actions/composer

      - name: Config Laravel
        uses: ./.github/actions/config-laravel

      - name: Run Test with Pest
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testdatabase
          DB_PORT: 33306
          DB_USER: user
          DB_PASSWORD: secret
        run: |
          php artisan migrate:fresh --seed
          ./vendor/bin/pest
